Dependency refresh
Fixing that:

> mocha --require ./test-hook -b tests/*.spec.js

/Users/ikr/Sandbox/react-room-occupancy-input/node_modules/jsdom-test-browser/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/ikr/Sandbox/react-room-occupancy-input/node_modules/jsdom-test-browser/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/ikr/Sandbox/react-room-occupancy-input/node_modules/jsdom-test-browser/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ikr/Sandbox/react-room-occupancy-input/node_modules/jsdom-test-browser/node_modules/jsdom/lib/jsdom/browser/index.js:14:21)
...